<?xml version="1.0"?>
<!DOCTYPE inex-topic-file [
<!ENTITY  lt      "lessthan">
<!ENTITY  gt      "greaterthan">
<!ENTITY  amp     "ampersand">
<!ELEMENT inex-topic-file (topic+)>
<!ELEMENT topic (title,castitle,phrasetitle,description,narrative)>
<!ATTLIST topic id CDATA #REQUIRED>
<!ATTLIST topic ct_no CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT castitle (#PCDATA)>
<!ELEMENT phrasetitle (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT narrative (#PCDATA)>
]>
<inex-topic-file>
<topic id="2009001" ct_no="186">
  <title>Nobel prize</title>
  <castitle>//article[about(., Nobel prize)]</castitle>
  <phrasetitle>"Nobel prize"</phrasetitle>
  <description>information about Nobel prize</description>
  <narrative>I need to prepare a presentation about the Nobel prize. Therefore, I want to collect information about it as much as possible. Information, the history of the Nobel prize or the stories of the award-winners for example, is in demand.  </narrative>
</topic>
<topic id="2009002" ct_no="187">
  <title>best movie</title>
  <castitle>//article[about(., best movie)]</castitle>
  <phrasetitle>best movie</phrasetitle>
  <description>information of classical movies</description>
  <narrative>I spend most of my free time seeing movies. Recently, I want to retrospect some classical movies.   Therefore, I need information about the awarded movies or movies with good reputation.   Any information, such as the description or comments of the awarded movies on famous filmfests or movies with good fame, is in demand.</narrative>
</topic>
<topic id="2009003" ct_no="188">
  <title>yoga exercise</title>
  <castitle>//article[about(.,yoga exercise)]</castitle>
  <phrasetitle>"yoga exercise"</phrasetitle>
  <description>information about yoga lesson</description>
  <narrative>Yoga is a good discipline for relaxing. 20 minutes yoga exercise can help people free body out of tension. I want to know some yoga methods for relaxing after long time work.  Thus, lessons of easy yoga which can be done in the office or at home are in demand.  Information on yoga history or different yoga denominations is not required.</narrative>
</topic>
<topic id="2009004" ct_no="189">
  <title>mean average precision reciprocal rank references precision recall proceedings journal</title>
  <castitle>//article[about(.//(sec|p),mean average precision reciprocal rank proceedings journal) and ( about(.//st,references) or about(.//st,see also) ) and about(.//image,precision recall)]</castitle>
  <phrasetitle>"mean average precision"  "reciprocal rank"  "precision recall"  "recall precision" "see also"</phrasetitle>
  <description>explain "mean average precision" and "reciprocal rank" with images  or plots.  Provide references in proceedings and journals</description>
  <narrative>I am a student enrolled in an Information Retrieval subject.  I need to write about the "mean average precision" and "reciprocal rank" and identify the similarities and differences in what they measure. Relevant text will define how these quantities are computed and what they mean.  Discussion about the similarities and differences are relevant, as are discussions of the use of these quantities in evaluation.  Images showing examples are relevant as is the text explaining the images.  I want to find references to articles that are related so that I can extend the search beyond the Wikipedia.</narrative>
</topic>
<topic id="2009005" ct_no="190">
  <title>chemists physicists scientists alchemists periodic table elements</title>
  <castitle>//article[about(.,periodic table elements chemists physicists scientists alchemists)]//(person|chemist|alchemist|scientist|physicist)</castitle>
  <phrasetitle> "periodic table"</phrasetitle>
  <description>I'd like to learn about people, chemists, physicists and even alchemists, who studied elements and the periodic table</description>
  <narrative>I am writing an essay on the discovery and development of the periodic table for a Chemistry class.  I'd like to learn about people, chemists, physicists and even alchemists, who studied elements and the periodic table.  I'm particularly interested in the names of the people so that I can follow up and research their work in more detail.  General information is also relevant - as long as it relates to the contribution of the people identified.</narrative>
</topic>
<topic id="2009006" ct_no="191">
  <title>opera singer italian spanish -soprano</title>
  <castitle>//(classical_music|opera|orchestra|performer|singer)[about(.,italian spanish opera singer -soprano)]</castitle>
  <phrasetitle>"opera singer"</phrasetitle>
  <description>I am interested in learning about male italian and spanish opera singers</description>
  <narrative>I am writing a book about male Italian and Spanish opera singers.  Only male Italian and Spanish singers are relevant, and all of them are relevant.</narrative>
</topic>
<topic id="2009007" ct_no="192">
  <title>financial and social man made catastrophes adversity misfortune -"natural disaster"</title>
  <castitle>//article[about(.//(misfortune|catastrophe|adversity),financial and social -"natural disaster" catastrophes)]</castitle>
  <phrasetitle>-"natural disaster" "financial misfortune" financial disaster" "financial catastrophe" "financial adversity" "social disaster" "social catastrophe"</phrasetitle>
  <description>find examples of major financial and social disaters and catastrophies that are not of natural causes but man made</description>
  <narrative>I am writing an article evaluating the cost of man made disasters.  I have a report on natural disasters like earthquakes, floods, tsunamis etc, so these are not of any interest in this query.  Here I am interested in man caused disasters like wars, stock exchange crashes (Synchronized Swimming?)</narrative>
</topic>
<topic id="2009008" ct_no="193">
  <title>israeli director actor actress film festival</title>
  <castitle>//article[about(.//(film_festival|movie|actor|actress),israeli director actor actress film festival)]</castitle>
  <phrasetitle>"israeli director"  "israeli actor" "israeli  actress" "film festival"</phrasetitle>
  <description>find information about Israeli actor, actresses and film directors and film festivals in which they appeared</description>
  <narrative>I would like to learn about the presence of Israeli film makers on the international stage for pre-interview research.  Of particular interest are actors and directors.  Not interested in general information about these people but specifically about their international exposure.</narrative>
</topic>
<topic id="2009009" ct_no="194">
  <title>election +victory australian labor party state council -federal</title>
  <castitle>//(p|sec)[about(.//(political_party|politics),election +victory australian labor party state council -federal)]</castitle>
  <phrasetitle>"election victory" "state election" "council election" "australian labor party"</phrasetitle>
  <description>find informationabout election victories of the australian labor party in state and council elections -federal</description>
  <narrative>I want to analyse Australian Labor Party victories in state and local elections.  Federal elections are of no interest.  Descriptions of the circumstances of the election are of interest.</narrative>
</topic>
<topic id="2009010" ct_no="195">
  <title>applications bayesian networks bioinformatics</title>
  <castitle>//*[about(.,applications bayesian networks bioinformatics)]</castitle>
  <phrasetitle> "bayesian networks"</phrasetitle>
  <description>Find information about applications of bayesian networks in the field of bioinformatics</description>
  <narrative>For my personal use, because one of my main areas of research is focused on Bayesian networks, I would like to find any kind of information concerning the applications of Bayesian networks to the field of bioinformatics. I am aware that many recent research effort is being devoted to this topic but I do not know much about it, so that any piece of information truly devoted to it is relevant.    To be relevant, a document or a document part should speak about both Bayesian networks and bioinformatics. Documents devoted only to Bayesian networks or to bioinformatics are not relevant.</narrative>
</topic>
<topic id="2009011" ct_no="196">
  <title>olive oil health benefit</title>
  <castitle>//food[about(., olive oil) and about(., health benefit)]</castitle>
  <phrasetitle>"olive oil" "health benefit"</phrasetitle>
  <description>Find information about what sort of health benefit olive oil has.</description>
  <narrative>I'm a health/beauty buff. I recently learned that olive oil is "good for you". What are the specific health/beauty benefits for consuming olive oil? Any article that mentions health benefits of olive oil is fine, EXCEPT those in which the claim is based on either unpopular/obscure or unscientific methods. So for example, if XXX diet recommends consuming olive oil then it's irrelevant. Note that since Mediterranean diet is not a weight-loss fat diet, but the traditional Mediterranean ways of eating, an article describing the health benefits of olive oil in this setting is relevant.     Anything outside of health benefit is irrelevant, how olive oil is produced, the different grades of olive oil etc.</narrative>
</topic>
<topic id="2009012" ct_no="197">
  <title>vitiligo pigment disorder cause treatment</title>
  <castitle>//article[about(., vitiligo) AND about(.//category, pigment disorder)]</castitle>
  <phrasetitle>"treatment of vitiligo", "cause of "vitiligo" "pigment disorder"</phrasetitle>
  <description>Find information on causes of vitiligo and treatment for it.</description>
  <narrative>I have a relative suffering from vitiligo, a skin depigmentation disease which leaves white patches on the skin. I would like information on the causes, treatment, possible treatment centers (like known clinics or centers that have cured this skin disease). Also, information on known people who suffer from it and may have found a cure would be helpful. Any historical or medically-related information on this skin disease would be relevant. Associations or any group helping people with psychological and emotional problems incurred by vitilgo will be relevant.   However, fantasy or miracle-type cures are not releveant. Also, homonyms like albums and music groups bearing this name are definitely not relevant.</narrative>
</topic>
<topic id="2009013" ct_no="198">
  <title>native american indian wars against colonial americans</title>
  <castitle>//article[about(.//conflict, native american indian wars against colonial americans)]</castitle>
  <phrasetitle>"native american" "american indian" "wars against colonial americans"</phrasetitle>
  <description>Find information on the native american wars against colonial settlers and federal troops in North america</description>
  <narrative>Recently, the Public Broadcasting Service aired a series of documentaries entitled "We shall remain" about the history of the native americans resistance to colonial occupation of their land, now known as the USA.This documentary was quite fascinating in that it shed a new light on the american indians, the protagonists and how they struggled to resist the colonial settlers and american expansionism. I would like to find articles that document the several wars fought from before the american revolution (1783) till the end of world war I (1917). For an article or passage to be relevant, it must include passages about these american indian wars. Articles on specific wars such as the Pequot wars or the Wounded knee massacre are relevant. Passages or articles about the forcible removal of indians to Indians reservations would also be relevant (e.g. Cherokee trail of tears). Articles about treaties signed between the native americans and the federal government are also relevant.  However articles about american indians in general documenting their tribes, beliefs or ways of life are not relevant if they do not include any passage about wars fought against the colonial settlers. Of no relevance also are articles about native american folkore or foods nor will be articles about wars involving the country India in Asia.</narrative>
</topic>
<topic id="2009014" ct_no="199">
  <title>content based image retrieval</title>
  <castitle>//*[about(., content based image retrieval)]</castitle>
  <phrasetitle>"content based" "image retrieval" "content based image retrieval"</phrasetitle>
  <description>image retrieval using the low level features</description>
  <narrative>I'm currently writing a report about image retrieval, and I'm searching some informations about the image retrieval based on visual content. I want to know also some systems based on visual features. Description of visual indexing and processing will be very interesting. Giving some examples of systems using this technique is relevant. On the other hand, information about the semantic gap and the visual image retrieval problems are not relevant.</narrative>
</topic>
<topic id="2009015" ct_no="200">
  <title>Voice over IP</title>
  <castitle>//*[about(.//section, voice over ip)]</castitle>
  <phrasetitle/>
  <description>voice over internet protocol technology</description>
  <narrative>I am currently preparing a course about voice over internet protocol. I am looking for information on this technology. More precisely I want to know its architecture and how it works. Information about only internet protocol without voice specification are not relevant. Information about softwares using Voice over Ip technique are not relevant.</narrative>
</topic>
<topic id="2009016" ct_no="201">
  <title>cycle road skill race</title>
  <castitle>//bicycle[about(., road bike race)]</castitle>
  <phrasetitle>"road bike" "road race"</phrasetitle>
  <description>Find information about how to improve my road cycling skills.</description>
  <narrative>I recently took up road cycling, and I want to improve my cycling skills so that I can become a good racer. Any elements related to non-road cycles, such as BMX and mountain biking is irrelevant. An element about a famous road cyclist is also irrelevant. An element about equipment for training for road race is relevant.</narrative>
</topic>
<topic id="2009017" ct_no="202">
  <title>rent buy home</title>
  <castitle>//home[about(.,home purchase rental)]</castitle>
  <phrasetitle/>
  <description>Find information about if I should buy or rent home.</description>
  <narrative>Many of my friends started owning a housing property, and since I have enough savings, I'm considering purchasing home sometimes soon. But I'm also a commitment-phobic, and I want to know all the important information to help me decide if I should indeed buy or just rent home. Any element discussing home buying is relevant, even if it does not compare against home renting. However, elements discussing purchasing or renting of a second home is irrelevant.</narrative>
</topic>
<topic id="2009018" ct_no="203">
  <title>Dwyane Wade</title>
  <castitle>//*[about(., Dwyane Wade)]</castitle>
  <phrasetitle>"Dwyane Wade"</phrasetitle>
  <description>Find information about the basketball  player Dwyane Wade from Miami Heats.</description>
  <narrative>As a big fan of Dwyane Wade, I would like to know everything about him, no matter his NBA career experience, nor his personal life.   Articles mainly talking about other NBA players with only a little mention of Dwyane Wade for he is once a teammate or they are friends are irrelevant. Articles talking about other people with the same surname or full name are irrelevant.   Articles focuses on Dwyane Wade are relevant. Articles talking about some NBA events which Dwyane Wade have participated are also relevant.    </narrative>
</topic>
<topic id="2009019" ct_no="204">
  <title>Latent semantic indexing</title>
  <castitle>//*[about(., Latent semantic indexing)]</castitle>
  <phrasetitle>"latent semantic indexing"</phrasetitle>
  <description>Find information about the probabilistic retrieval model named latent semantic indexing.</description>
  <narrative>As a student learning information retrieval, latent semantic indexing is a very important probabilistic retrieving model. I would like to get a comprehensive understanding of latent semantic indexing.  Obviously, articles talking about latent semantic indexing are relevant. In addition, articles explain the concept about latent semantic or the implications of latent semantic are also relevant.  Latent semantic is different from semantic. Articles talking about other semantic topics such as semantic web or semantic mapping are irrelevant. Articles talking about other retrieval models with only a little mention of latent semantic indexing without explaining it are irrelevant.</narrative>
</topic>
<topic id="2009020" ct_no="205">
  <title>IBM computer</title>
  <castitle>//article[about(.,IBM)]//sec[about(., computer)]</castitle>
  <phrasetitle>"IBM computer"</phrasetitle>
  <description>I want to find some information about IBM computer.</description>
  <narrative>Personally, I like to use IBM's products very much, I would like to gain knowledge of IBM's computer products more deeply. If the article relates to IBM's computer products, talks about its models, functions and introductions, then it is considered relevant.</narrative>
</topic>
<topic id="2009021" ct_no="206">
  <title>wonder girls</title>
  <castitle>//article[about(.,"wonder girls")]</castitle>
  <phrasetitle>"wonder girls"</phrasetitle>
  <description>I want to find some information about the famous South Korean group "wonder girls".</description>
  <narrative>"Wonder Girls" is a South Korean girl group. It is a very popular group with its famous songs, such as "tell me" and "nobody". If the article contains the introduction of the group or of its albums and songs, then I consider it relevant.</narrative>
</topic>
<topic id="2009022" ct_no="207">
  <title>Szechwan dish food cuisine</title>
  <castitle>//article[about(.,cuisine) or about(.,dish) or about(.,food)]//sec[about(.,Szechwan) or about(.,Sichuan)]</castitle>
  <phrasetitle>"Szechwan dish" "Szechwan food" "Szechwan cuisine"</phrasetitle>
  <description>I want to find some famous Szechwan dishes.</description>
  <narrative>I am a Chinese, and I like the Szechwan dish very much. I want to find some famous Szechwan dishes, so the information about the dishes of Szechwan food is relevant. But the information about the chef, the restaurant or other dishes is irrelevant.</narrative>
</topic>
<topic id="2009023" ct_no="208">
  <title>"plays of Shakespeare"+Macbeth</title>
  <castitle>//article[about(.,"plays of Shakespeare") or about(., Macbeth)]//sec[about(., Macbeth)]</castitle>
  <phrasetitle>"plays of Shakespeare" </phrasetitle>
  <description>I want to find some famous plays of Shakespeare, especially the "Macbeth".</description>
  <narrative>Shakespeare is very famous, my teacher always talks about Shakespeare's work. So, I want to know some famous plays of Shakespeare, especially "Macbeth" which is my teacher's favorite. Life, arts or styles about Shakespeare, information about other writer's plays and the films or famous actors of Shakespeare's plays are irrelevant. Information about the plays of Shakespeare, especially "Macbeth‚Äù, and roles or places in Shakespeare's plays are relevant.</narrative>
</topic>
<topic id="2009024" ct_no="209">
  <title>cloud computing</title>
  <castitle>//article[about(.,"cloud computing")]</castitle>
  <phrasetitle>"cloud computing"</phrasetitle>
  <description>I want to get some information about cloud computing.</description>
  <narrative>Cloud computing is a new technology now. So I want to get some information about cloud computing. Knowledge, information, researcher, provider, software, system and platform using or about clouding computing are relevant.</narrative>
</topic>
<topic id="2009025" ct_no="210">
  <title>scenic spot in Beijing</title>
  <castitle>//article[about(.,scenic spot) and about(.,Beijing)]</castitle>
  <phrasetitle>"scenic spot" </phrasetitle>
  <description>I want to find some scenic spots in Beijing.</description>
  <narrative>Beijing is the capital of China. This summer, I want to travel to Beijing, so I want to find some scenic spots in Beijing. Scenic spots in other cities are irrelevant.</narrative>
</topic>
<topic id="2009026" ct_no="211">
  <title>generalife gardens</title>
  <castitle>//*[about(.//site,generalife) and about(.//category,gardens)]</castitle>
  <phrasetitle/>
  <description>Find information about the gardens of Generalife</description>
  <narrative>The world famous gardens of Generalife are located at Granada, Spain, near the Alhambra palace. I live in Granada, and I would like to know what kind of information about the Generalife exists in the web.  To be relevant a document or document part should contain some piece of information about the Generalife gardens. Documents about other famous gardens are not relevant. Document which only mention the word generalife without adding some information are not relevant. Document using the word generalife to refer to another thing (e.g. a song or a ship) are not relevant.</narrative>
</topic>
<topic id="2009027" ct_no="212">
  <title>Zhang Yimou</title>
  <castitle>//*[about(., Zhang Yimou)]</castitle>
  <phrasetitle>"Zhang Yimou"</phrasetitle>
  <description>Find information about the great film maker named Zhang Yimou.</description>
  <narrative>After the 2008 Olympic Game in Beijing, the amazing opening ceremony gives people all over the world a comprehensive view of China's great history. At the same time, Zhang Yimou, as the director of the ceremony, who is widely known as one of the fifth generation movie directors of China, earned a legendary amount of fame. I become interested in his past experiences. So, I would like to find information about his background, his films and his great career experience.  Articles introducing Zhang Yimou, his films or awards he was once rewarded are all relevant.  Articles talking about other film directors, with only a mention of Zhang Yimou's name only for they are the same class of directors or they have once worked together, without any information about Zhang's life experiences, are irrelevant. Articles talking about those great actors or actresses once appeared in Zhang's films, focusing only on the personal life them, without any explanation of how he/she work together with Zhang, are irrelevant.</narrative>
</topic>
<topic id="2009028" ct_no="213">
  <title>fastest speed bike scooter car motorcycle</title>
  <castitle>//vehicles[about(., fastest speed)]</castitle>
  <phrasetitle/>
  <description>I want to know vehicles and its speed capacity.</description>
  <narrative>I'm still hesitant to buy a car, and considering other modes of trasnportation. Cars may be able to give out the fastest speed, but in urban area, the speed limit is 40km/h. Thus, I'm wondering if other methods of transportation could reach the same speed as cars drive in the urban area.     An element describing a fastest speed for any vehicles in general term is relevant. If an element was on a max speed of a specific brand of a vehicle, such as Toyota Prius, then it is irrelevant. An element describing the traffic laws for the max speed of any vehicle (in general term) is also relevant.</narrative>
</topic>
<topic id="2009029" ct_no="214">
  <title>personality type career famous</title>
  <castitle>//personality[about(., career) or about(., type)]</castitle>
  <phrasetitle>"personality type"</phrasetitle>
  <description>Find information that describes different personality types and career suited for the types, with famous people as an example.</description>
  <narrative>I'm interested in what kind of personality type I am, and which career I'm suited for. I'm also interested in roles models, i.e. famous people, in each type.    An element describing personality type and the famous people in the type as well as career suited for the type is relevant. An element describing a famous person's personality as in gregarious, easy-going, as opposed to personality type defined by an established source (INTJ etc.) and the person's career is irrevant.</narrative>
</topic>
<topic id="2009030" ct_no="215">

  <title>popular dog cartoon character</title>
  <castitle>//dog[about(., popular cartoon character)]</castitle>
  <phrasetitle>"cartoon character"</phrasetitle>
  <description>Find information about popular cartoon dog charactor.</description>
  <narrative>I like Snoopy and I'd like to know if there's any other popular canine cartoon charactor. An element about the character itself is relevant. An element about the show, in which the charactor is one of the main charactor is relevant. However, if the charactor is one of the side charactor, then the element out the show is irrelevant. An element about the person who created the canine charactor is irrelevant.</narrative>
</topic>
<topic id="2009031" ct_no="216">
  <title>sabre</title>
  <castitle>//article[about(.,sabre) ]</castitle>
  <phrasetitle/>
  <description>Find information about sabre techniques and sabre fencers.</description>
  <narrative>I am practicing sabre for one year, and I like to get more information about the sabre technique and the sabre fencers.     Relevant documents should contain information about the history of the sabre itself as a weapon, or information about the weaponj itsef,  or information about the rules and the practice of sabre. Concerning the sabre fencer, any fencer with the medals or titles won are also relevant for   me, as I like to have information abour the country that are successfull in this sport.</narrative>
</topic>
<topic id="2009032" ct_no="217">
  <title>evidence theory dempster schafer</title>
  <castitle>//article[ about(.,"evidence theory") or about(.,"dempster schafer") ]</castitle>
  <phrasetitle>"evidence theory" "dempster schafer"</phrasetitle>
  <description>Find information about Dempster Schafer theory of evidence.</description>
  <narrative>I am interested on finding all the data on the Dempster Schafer theory of evidence.    Relevant information should describe the fundamentals of this theory, as well as new works that have been done on  this theory like the belief tranferrable model. Documents explaining links with the probability theory are also  relevant.</narrative>
</topic>
<topic id="2009033" ct_no="218">
  <title>Al-Andalus taifa kingdoms</title>
  <castitle>//*[about(.,Al-Andalus taifa kingdoms)]</castitle>
  <phrasetitle>"taifa kingdoms" </phrasetitle>
  <description>Find all the relevant material related to the taifa kingdoms in Al-Andalus</description>
  <narrative>I like a lot the history of Spain in its middle ages, above all that related to the muslim period (from 8th to 15th centuries), so I enjoy a lot reading about this time. A significative moment during this domination is the Taifa kingdoms, where Al-Andalus was fragmented in lots of small regions ruled by a king. Then a document or a part of it is relevant if it deals with any of the aspects (territory, history, rulers, economy, wars, etc.) related to any of the Taifa kingdom across Al-Andalus. Documents or elements about taifa out of the context of Al-Andalus history are not relevant.</narrative>
</topic>
<topic id="2009034" ct_no="219">
  <title>the evolution of the moon</title>
  <castitle>//*[about(., the evolution of the moon)]</castitle>
  <phrasetitle/>
  <description>Find information about the origin and evolution of the moon.</description>
  <narrative>Human exploration of the moon has found that there are a lot of mysterious phenomena, and now scientists haven't yet found a reasonable explanation. If we want to understand those mysterious phenomena, we need to first make clear the origin and evolution of the moon.  Articles talking about the origin and evolution of the moon are relevant. Articles introducing mysterious phenomena happened on the moon are relevant, too.  Articles introducing human exploration experiences of the moon or relevant organizations, instruments, events are irrelevant.</narrative>
</topic>
<topic id="2009035" ct_no="220">
  <title>Bermuda Triangle</title>
  <castitle>//*[about(., Bermuda Triangle)]</castitle>
  <phrasetitle>"Bermuda Triangle"</phrasetitle>
  <description>Find information about the Bermuda Triangle.</description>
  <narrative>The Bermuda Triangle is a miracle, where many mysterious things have happened and still yet no reasonable explanation available. I would like to know everything about the Bermuda Triangle.  Articles introducing the Bermuda Triangle, mysterious things which happened in the Bermuda Triangle, scientific findings about the Bermuda Triangle, or even guesswork about the Bermuda Triangle are relevant.  Articles focusing on other topics with only a little mention of the phrase Bermuda Triangle without further discussing about it are irrelevant.</narrative>
</topic>
<topic id="2009036" ct_no="221">
  <title>notting hill film actors</title>
  <castitle>//*[about(.,notting hill actors) and about(.//category,film)]</castitle>
  <phrasetitle>"notting hill" "film actors"</phrasetitle>
  <description>Find information about the starring of "Notting hill" film</description>
  <narrative>Notting hill is my fauvorite film and I would like to know who are the actors of the film and if it is possible all the information about them. For this reason, I consider relevant documents or relevant parts, all of them that have information about the film and the actors or only about the actors like biography, projects, ...</narrative>
</topic>